#!/usr/bin/env python3
"""
Generate the slim API data module bundled by the Netlify Functions.

Emits a JavaScript file (not JSON) exporting a flat array of stations with
pre-normalized name and locality fields. Two reasons for the .js choice:
  * V8 lazy-parses bundled JS and caches compiled forms across container
    invocations, so cold-start cost is much lower than JSON.parse over a
    bundled JSON file.
  * The build step also strips fields the API doesn't expose (voting, parties,
    voter_count, number) and emits short field names ("n", "nl") to shave size.

All stations are included, mapped or not. Unmapped stations get lat=null and
lon=null; the /nearby handler is expected to skip them, and /search returns
them with geo.lat=null/geo.lon=null.

Usage:
    python3 scripts/generate_api_data.py <input.json> <output.js>
"""

import json
import sys
import unicodedata

CYR_TO_LAT = {
    'А': 'A', 'Б': 'B', 'В': 'V', 'Г': 'G', 'Д': 'D', 'Ђ': 'Đ', 'Е': 'E',
    'Ж': 'Ž', 'З': 'Z', 'И': 'I', 'Ј': 'J', 'К': 'K', 'Л': 'L', 'Љ': 'Lj',
    'М': 'M', 'Н': 'N', 'Њ': 'Nj', 'О': 'O', 'П': 'P', 'Р': 'R', 'С': 'S',
    'Т': 'T', 'Ћ': 'Ć', 'У': 'U', 'Ф': 'F', 'Х': 'H', 'Ц': 'C', 'Ч': 'Č',
    'Џ': 'Dž', 'Ш': 'Š',
    'а': 'a', 'б': 'b', 'в': 'v', 'г': 'g', 'д': 'd', 'ђ': 'đ', 'е': 'e',
    'ж': 'ž', 'з': 'z', 'и': 'i', 'ј': 'j', 'к': 'k', 'л': 'l', 'љ': 'lj',
    'м': 'm', 'н': 'n', 'њ': 'nj', 'о': 'o', 'п': 'p', 'р': 'r', 'с': 's',
    'т': 't', 'ћ': 'ć', 'у': 'u', 'ф': 'f', 'х': 'h', 'ц': 'c', 'ч': 'č',
    'џ': 'dž', 'ш': 'š',
}


def cyr_to_lat(s: str) -> str:
    return ''.join(CYR_TO_LAT.get(ch, ch) for ch in s)


def normalize(s: str) -> str:
    if not s:
        return ''
    decomposed = unicodedata.normalize('NFD', cyr_to_lat(s))
    stripped = ''.join(ch for ch in decomposed if not unicodedata.combining(ch))
    return stripped.lower()


def main(src: str, dst: str) -> None:
    with open(src, 'r', encoding='utf-8') as f:
        data = json.load(f)

    rows = []
    total = 0
    mapped = 0
    unmapped = 0
    for loc in data.get('localities', []):
        locality_id = loc['id']
        locality_name = loc['name']
        locality_norm = normalize(locality_name)
        for st in loc.get('polling_stations', []):
            total += 1
            geo = st.get('geo') or {}
            lat = geo.get('lat')
            lon = geo.get('lon')
            if isinstance(lat, (int, float)) and isinstance(lon, (int, float)):
                mapped += 1
            else:
                lat = None
                lon = None
                unmapped += 1
            rows.append({
                'id': st['id'],
                'name': st['name'],
                'localityId': locality_id,
                'localityName': locality_name,
                'lat': lat,
                'lon': lon,
                'n': normalize(st['name']),
                'nl': locality_norm,
            })

    payload = json.dumps(rows, ensure_ascii=False, separators=(',', ':'))

    with open(dst, 'w', encoding='utf-8') as f:
        f.write(f'// GENERATED by scripts/generate_api_data.py from {src}\n')
        f.write(f'// total={total} mapped={mapped} unmapped={unmapped}\n')
        f.write(f'module.exports = {payload};\n')

    import os
    size = os.path.getsize(dst)
    print(f'Wrote {dst} ({size:,} bytes, {size/1024/1024:.2f} MB)')
    print(f'  total={total} mapped={mapped} unmapped={unmapped}')


if __name__ == '__main__':
    if len(sys.argv) != 3:
        print('Usage: python3 scripts/generate_api_data.py <input.json> <output.js>', file=sys.stderr)
        sys.exit(1)
    main(sys.argv[1], sys.argv[2])
